In [19]:
import pandas as pd
import numpy as np

In [20]:
train = pd.read_csv('data/train.csv')
test = pd.read_csv('data/test.csv')

In [21]:
train

                   ImageID
0      6119677716839104391
1     14802949761255250525
2     14124813423892560492
3      5482257461254211163
4     10081435122427592003
...                    ...
2616   9060386186086836431
2617   3583815641843563968
2618   2719679196594321269
2619  15043768931442006468
2620   9722418938962263447

[2621 rows x 1 columns]

In [22]:
test

                  ImageID
0     9743172603816335085
1    17004858536531882177
2    14154985252110231409
3    16192052287592277289
4     9813974023071101620
..                    ...
643   9192582588348387279
644    626987530498234511
645   1168137846853679068
646   7883619200384457433
647   4614757289603386106

[648 rows x 1 columns]

In [23]:
train_series = train['ImageID']
test_series = test['ImageID']
train_series[train_series.isin(test_series)]

Series([], Name: ImageID, dtype: uint64)